#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt clobber
unsetopt nomatch
unsetopt correct

if [ -f "${HOME}/.aliases" ]; then
    source "${HOME}/.aliases"
fi

if [ -f "${HOME}/.profile" ]; then
    source "${HOME}/.profile"
fi

bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

wal -i "$(gsettings get org.gnome.desktop.background picture-uri | sed 's+file://++' | xargs)" -t

