#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt clobber
unsetopt nomatch
unsetopt correct
export PATH=$PATH:/usr/local/kea/bin:/usr/local/kea/sbin:/usr/local/dt-kea-config-tool-kea-config-tool/bin:/usr/local/dt-kea-config-tool-kea-config-tool/sbin
export CQLSH_NO_BUNDLED=true

if [ -f $HOME/.aliases ]; then
    source $HOME/.aliases
fi
export VISUAL=nvim
export EDITOR="$VISUAL"
export HISTSIZE=9999999
export SAVEHIST=9999999
bindkey "${terminfo[khome]}" beginning-of-line
bindkey "${terminfo[kend]}" end-of-line
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

export JENKINS_APP_TOKEN=sadfsdajfdafjadsjfadsjfadslads
export JENKINS_AUTH_TOKEN=e48db72445c9d470fc099cd4d33ecad7
export JENKINS_USER=andrei.pavel

